url: "https://bigearth.net"
base_url: ""
title: BigEarthNet
email: contact@bigearth.eu
description: >- # this means to ignore newlines until "baseurl:"
  BigEarthNet is a benchmark archive, consisting of 590,326 pairs of
  Sentinel-1 and Sentinel-2 image patches. The first version (v1.0-beta)
  of BigEarthNet includes only Sentinel 2 images. Recently,
  it has been enriched by Sentinel-1 images to create a multi-modal
  BigEarthNet benchmark archive (called also as BigEarthNet-MM).